#
#  Configuration for e2e.workflow
#

gulp:
  watch:
    jsdoc:
      - 'index.js'
      - 'gulpfile.js'
      - 'server.js'
      - 'gulp/**/*.js'
      - 'src/**/*.js'
    jshint:
      - '*.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'src/**/*.js'
      - 'config/modules/**/tests/e2e-workflow/*.js'
    jsonlint:
      - '*.json'
      - '.jscsrc'
      - '.jshintrc'
      - '.lesshintrc'
    yamllint:
      - '**/*.yaml'
      - '**/*.yml'
    less:
      - 'src/less/app.less'
      - 'src/less/**/*.less'
    puglint:
      - 'views/**/*.pug'
    server-restart:
      - './server.js'
      - 'lib/config.js'
      - 'lib/ipv4addresses.js'
    test-e2e-workflow-default:
      - 'index.js'
      - 'config/default.js'
      - 'lib/log.js'
    test-e2e-workflow-modules:
      - 'config/modules/vcards/**/*'
    livereload:
      - 'htdocs/**/*.html'
      - 'views/**/*.pug'
      - 'htdocs/img/**/*.*'
      - 'htdocs/css/app.css'
      - 'htdocs/js/**/*.js'
      - 'results/modules/**/*.json'
  build:
    jsdoc:
      src:
        - 'index.js'
        - 'gulpfile.js'
        - 'server.js'
        - 'gulp/**/*.js'
        - 'lib/**/*.js'
        - 'src/**/*.js'
      dest: 'docs/jsdoc'
    js:
      src: 'src/js/*.js'
      dest: 'htdocs/js'
      replace:
        '/js': ''
    less:
      src: 'src/less/app.less'
      dest: 'htdocs/css'
  tests:
    test-e2e-workflow-default:
      default: 'config/default.js'
    test-e2e-workflow-modules:
      default: 'config/default.js'
      vcards: 'config/modules/vcards/tests/e2e-workflow/*.js'

server:
  server: ./server.js
  docroot: ./htdocs
  modules: .
  httpPort: 8080
  livereloadPort: 8081
  verbose: false
