#
#  Configuration for gulp expressjs projects
#
gulp:
  start:
    development:
      gulp:
        - 'lint'
        - 'build'
        - 'watch'
        - 'livereload-start'
        - 'server-start'
        - 'tests'
        - 'livereload'
#        - 'livereload-all'
        - 'eslint'
      build:
        - 'less'
        - 'js'
        - 'locales'
        - 'jsdoc'
      tests:
        - 'test-modules'
      lint:
        - 'ejslint'
        - 'eslint'
        - 'jsonlint'
        - 'yamllint'
        - 'puglint'
      server:
        - 'server-changed'
        - 'tests'
    staging:
      gulp:
        - 'watch'
        - 'livereload-start'
        - 'server-start'
        - 'livereload'
        - 'eslint'
      build:
        - 'less'
        - 'js'
        - 'locales'
      tests: []
      lint:
        - 'eslint'
        - 'yamllint'
        - 'puglint'
        - 'lesshint'
      server:
        - 'server-changed'
      watch:
        - 'server'
        - 'livereload'
        - 'eslint'
        - 'js'
        - 'yamllint'
        - 'puglint'
        - 'less'
        - 'livereload-all'
        - 'test-modules'
        - 'test-e2e-workflow-modules'
    production:
      gulp:
        - 'build'
        - 'server-start'
      build:
        - 'less'
        - 'js'
        - 'locales'
      tests: []
      lint: []
      server:
        - 'server-changed'
      watch:
        - 'test-e2e-workflow-modules'
  watch:
    eslint:
      - 'gulpfile.js'
      - '.eslintrc.js'
      - 'gulp/**/*.js'
    js:
      - 'modules/*/js/*.js'
    jsdoc:
      - '*.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'modules/**/*.js'
    jsonlint:
      - '**/*.json'
      - '.lesshintrc'
      - '!coverage/**/*.json'
      - '!src/locales/*.json'
      - '!modules/**/locales/*.json'
    locales:
      - 'src/locales/*.json'
      - 'modules/**/locales/*.json'
    yamllint:
      - '**/*.yaml'
      - '**/*.yml'
    ejslint-livereload:
      - '**/*.ejs'
    less:
      - 'src/less/**/*.less'
      - 'modules/**/*.less'
    puglint:
      - '**/*.pug'
    server:
      - 'server.js'
      - 'lib/*.js'
      - 'modules/*/server/**/*.js'
      - 'modules/*/*.yaml'
    livereload:
      - 'public/**/*.html'
      - 'public/img/**/*.*'
      - 'generated/**/*.css'
      - 'modules/**/*.ejs'
      - 'modules/**/*.pug'
      - 'results/modules/**/*.json'
    livereload-all:
      - 'generated/**/*.js'
      - 'locales/**/*.*'
    test-modules:
      - '*.js'
      - 'modules/**/tests/model/*.*'
      - 'modules/**/tests/server/*.*'
      - 'modules/**/views/**/*.*'
      - 'htdocs/js/**/*.js'
    test-e2e-workflow-modules:
      - 'config/**/js/**/*.js'
      - 'config/**/less/**/*.less'
      - 'config/**/server/**/*.js'
      - 'config/**/tests/e2e-workflow/*.js'
      - 'config/**/views/**/*.*'
  tests:
    modules:
      - 'modules/**/tests/model/*.js'
      - 'modules/**/tests/server/*.js'
      - 'modules/**/tests/views/*.js'
    test-e2e-workflow-modules:
      - 'config/**/tests/e2e-workflow/*.js'
  lint:
    eslint:
      files:
        - '*.js'
        - '.eslintrc.js'
        - 'gulp/**/*.js'
        - 'lib/**/*.js'
        - 'modules/**/*.js'
      fixtureDir: './fixture'
  build:
    jsdoc:
      src:
        - '*.js'
        - 'gulp/**/*.js'
        - 'lib/**/*.js'
        - 'modules/**/*.js'
        - 'src/**/*.js'
      dest: 'docs/jsdoc'
    js:
      src:
        - 'modules/*/js/*.js'
      dest: 'generated'
      replace:
        'modules/(.+/)js/.+': '$1'
    less:
      src:
        - 'src/less/app.less'
        - 'modules/*/less/layout.less'
      dest: 'generated'
    locales:
      dest: 'locales'
    deploy:
      src:
        - 'CHANGELOG.md'
        - 'configuration.yaml'
        - 'Dockerfile'
        - 'LICENSE'
        - 'package.json'
        - 'README.md'
        - 'server.js'
        - 'generated/*'
        - 'lib/**/*'
        - 'locales/*'
        - 'modules/*/*.json'
        - 'modules/*/*.yaml'
        - 'modules/*/server/**/*'
        - 'modules/*/views/**/*'
        - 'public/**/*'
      dest: 'deploy'

server:
  server: ./server.js
  docroot: ./public
  generated: ./generated
  modules: ./modules
  verbose: false
  httpsKey: ./key/selfsigned.key
  httpsCert: ./key/selfsigned.crt
