# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3"

services:

  hub:
    image: selenium/hub:3.12.0-boron
    container_name: hub
    hostname: hub
    networks:
      - vcards

  chrome:
    image: selenium/node-chrome:3.12.0-boron
    container_name: chrome
    depends_on:
      - hub
    networks:
      - vcards
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING

  firefox:
    image: selenium/node-firefox:3.12.0-boron
    container_name: firefox
    depends_on:
      - hub
    networks:
      - vcards
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING

  e2e-workflow:
    build:
      context: .
    image: uwegerdes/e2e-workflow
    container_name: e2e-workflow
    hostname: e2e-workflow
    ports:
      - 51380:8080
      - 51381:8081
    depends_on:
      - hub
    networks:
      - vcards
    volumes:
      - .:/home/node/app
      - ../docker-vcards/modules:/home/node/app/config/modules
#    command: gulp --silent
    command: npm run dev

networks:
  vcards:
    external:
      name: vcards-bridge
