# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3"

services:

  e2e-hub:
    image: selenium/hub:3.12.0-boron
    container_name: e2e-hub
    hostname: e2e-hub

  e2e-chrome:
    image: selenium/node-chrome:3.12.0-boron
    container_name: e2e-chrome
    depends_on:
      - e2e-hub
    environment:
      - HUB_HOST=e2e-hub
      - HUB_PORT=4444
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING

  e2e-firefox:
    image: selenium/node-firefox:3.12.0-boron
    container_name: e2e-firefox
    depends_on:
      - e2e-hub
    environment:
      - HUB_HOST=e2e-hub
      - HUB_PORT=4444
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING

  e2e-workflow:
    build:
      context: .
    image: uwegerdes/e2e-workflow
    container_name: e2e-workflow
    hostname: e2e-workflow
    ports:
      - 51380:8080
      - 51381:8081
    depends_on:
      - e2e-hub
    volumes:
      - .:/home/node/app
#      - ../docker-vcards/modules:/home/node/app/config/modules
#    command: gulp --silent
    command: npm run dev
